Repository stefanprodan/timoni, pull requests merged in 2023-05, with the labels that each got.

#91 feat: enable name-oriented bundle management
  README.md
  api/v1alpha1/bundle.go
  cmd/timoni/apply.go
  cmd/timoni/apply_test.go
  cmd/timoni/bundle_apply.go
  cmd/timoni/bundle_apply_test.go
  cmd/timoni/bundle_delete.go
  cmd/timoni/bundle_delete_test.go
  cmd/timoni/bundle_lint.go
  cmd/timoni/bundle_lint_test.go
  cmd/timoni/list.go
  docs/bundles.md
  examples/bundles/podinfo.cue
  internal/engine/bundle_builder.go
  internal/runtime/storage.go
Labels: enhancement, area/bundles

#87 Improve how `GetResource` works
  internal/engine/resourceset.go
Labels: area/engine

#93 Introduce instance schema and module linting
  api/v1alpha1/bundle.go
  api/v1alpha1/instance.go
  api/v1alpha1/inventory.go
  api/v1alpha1/module.go
  api/v1alpha1/selector.go
  cmd/timoni/apply.go
  cmd/timoni/build.go
  cmd/timoni/bundle_apply.go
  cmd/timoni/inspect_module.go
  cmd/timoni/mod_lint.go
  cmd/timoni/mod_lint_test.go
  cmd/timoni/mod_push.go
  internal/engine/bundle_builder.go
  internal/engine/fetcher.go
  internal/engine/module_builder.go
  internal/engine/resourceset.go
  internal/engine/values_builder.go
  internal/runtime/storage.go
Labels: area/api, area/cli, area/engine

#100 Add support for `timoni.ignore`
  api/v1alpha1/ignore.go
  cmd/timoni/mod_init.go
  cmd/timoni/mod_pull_test.go
  cmd/timoni/mod_push.go
  cmd/timoni/testdata/module/ignore/ignore.txt
  cmd/timoni/testdata/module/timoni.ignore
  docs/module.md
  go.mod
  go.sum
  internal/engine/testdata/module/ignore/ignore.txt
  internal/engine/testdata/module/ignore_tool.cue
  internal/engine/testdata/module/timoni.ignore
  internal/engine/utils.go
  internal/engine/utils_test.go
Labels: enhancement, area/api, area/engine

#101 Fix apply dry-run for new namespaces
  cmd/timoni/apply.go
  cmd/timoni/bundle_apply.go
Labels: area/cli

#104 Add security policy
  SECURITY.md
Labels: area/docs

#105 Generate SLSA3+ Provenance for Timoni binaries
  .github/workflows/release.yaml
Labels: area/ci

#106 Document SLSA Provenance & SBOMs
  README.md
  docs/install.md
Labels: area/docs

#111 Update cue to v0.5.0
  go.mod
  go.sum
Labels: area/engine, dependencies

#112 Add pretty print for logs and diff output
  cmd/timoni/apply.go
  cmd/timoni/bundle_apply.go
  cmd/timoni/bundle_delete.go
  cmd/timoni/bundle_lint.go
  cmd/timoni/delete.go
  cmd/timoni/dyff.go
  cmd/timoni/log.go
  cmd/timoni/main.go
  cmd/timoni/main_test.go
  cmd/timoni/mod_init.go
  cmd/timoni/mod_lint.go
  cmd/timoni/mod_list.go
  cmd/timoni/mod_pull.go
  cmd/timoni/status.go
  go.mod
  go.sum
Labels: area/ux, area/cli

#113 Increase default timeout to 5m
  cmd/timoni/main.go
Labels: area/cli

#115 Map the timeout flag to apply wait operations
  cmd/timoni/apply.go
  cmd/timoni/bundle_apply.go
Labels: area/cli

#116 Add the CUE version to `timoni version` output
  cmd/timoni/main.go
  cmd/timoni/version.go
Labels: area/cli

#117 Merge the bundle values with the module defaults
  cmd/timoni/bundle_apply.go
  internal/engine/module_builder.go
Labels: bug, area/bundles

#118 Add Helm comparison to docs
  README.md
  docs/comparison.md
  docs/index.md
  mkdocs.yml
Labels: area/docs

#119 docs: Normalise page titles
  docs/comparison.md
  mkdocs.yml
Labels: area/docs
