Repository stefanprodan/timoni, pull requests merged in 2023-12, with the labels that each got.

#263 Improve Timoni's CUE `#Metadata` schema
  Makefile
  schemas/timoni.sh/core/v1alpha1/metadata.cue
  schemas/timoni.sh/core/v1alpha1/selector.cue
Labels: area/api

#264 Add instance definitions to Timoni's CUE schemas
  schemas/timoni.sh/core/v1alpha1/instance.cue
  schemas/timoni.sh/core/v1alpha1/metadata.cue
  schemas/timoni.sh/core/v1alpha1/selector.cue
Labels: area/api

#276 Update `cuelang.org/go` to v0.7.0
  examples/minimal/templates/config.cue
  examples/minimal/templates/deployment.cue
  examples/minimal/templates/service.cue
  examples/minimal/timoni.cue
  examples/redis/templates/config.cue
  examples/redis/timoni.cue
  go.mod
  go.sum
Labels: dependencies

#272 Add `--name` flag to `timoni mod vet` command
  cmd/timoni/main_test.go
  cmd/timoni/mod_vet.go
  cmd/timoni/mod_vet_test.go
Labels: area/cli

#270 Add `#MetaComponent` generator to Timoni's CUE schemas
  schemas/timoni.sh/core/v1alpha1/metadata.cue
  schemas/timoni.sh/core/v1alpha1/selector.cue
Labels: area/api

#280 Refactor init module
  README.md
  cmd/timoni/main.go
  docs/module.md
  examples/minimal/README.md
  examples/minimal/cue.mod/pkg/timoni.sh/core/v1alpha1/image.cue
  examples/minimal/cue.mod/pkg/timoni.sh/core/v1alpha1/instance.cue
  examples/minimal/cue.mod/pkg/timoni.sh/core/v1alpha1/metadata.cue
  examples/minimal/cue.mod/pkg/timoni.sh/core/v1alpha1/requirements.cue
  examples/minimal/cue.mod/pkg/timoni.sh/core/v1alpha1/selector.cue
  examples/minimal/cue.mod/pkg/timoni.sh/core/v1alpha1/semver.cue
  examples/minimal/templates/config.cue
  examples/minimal/templates/deployment.cue
  examples/minimal/templates/job.cue
  examples/minimal/templates/service.cue
Labels: area/docs

#283 Document the Timoni's CUE schemas
  examples/minimal/cue.mod/pkg/timoni.sh/core/v1alpha1/selector.cue
  examples/redis/cue.mod/pkg/timoni.sh/core/v1alpha1/selector.cue
  schemas/README.md
  schemas/timoni.sh/core/v1alpha1/selector.cue
Labels: area/docs

#281 Add `timoni artifact tag` command
  cmd/timoni/artifact_push.go
  cmd/timoni/artifact_tag.go
  cmd/timoni/artifact_tag_test.go
  docs/bundle-distribution.md
  mkdocs.yml
Labels: area/cli, area/oci

#284 Document `managed-by` label usage
  docs/module.md
  examples/minimal/cue.mod/pkg/timoni.sh/core/v1alpha1/metadata.cue
  examples/redis/cue.mod/pkg/timoni.sh/core/v1alpha1/metadata.cue
  schemas/README.md
  schemas/timoni.sh/core/v1alpha1/metadata.cue
Labels: area/docs

#292 Add `--values` arg to `timoni mod vet` cmd
  cmd/timoni/mod_vet.go
  cmd/timoni/mod_vet_test.go
Labels: area/cli

#291 Add `--blueprint` arg to `timoni mod init` cmd
  cmd/timoni/mod_init.go
Labels: area/ux, area/cli

#293 Add `#ObjectReference` to Timoni's CUE schemas
  examples/minimal/README.md
  examples/minimal/cue.mod/pkg/timoni.sh/core/v1alpha1/object.cue
  examples/minimal/templates/config.cue
  schemas/README.md
  schemas/timoni.sh/core/v1alpha1/object.cue
Labels: area/api

#279 Fix `x-kubernetes-preserve-unknown-fields` path mismatch
  internal/engine/importer.go
  internal/engine/importer_test.go
Labels: area/engine

#294 docs: Format code blocks with CUE v0.7.0
  .github/workflows/docs.yaml
  Makefile
  docs/bundle-multi-cluster.md
  docs/bundle-runtime.md
  docs/bundle-secrets.md
  docs/bundle.md
  docs/concepts.md
  docs/module-distribution.md
  docs/module.md
  docs/quickstart.md
Labels: area/docs

#303 ci: Push blueprints on-demand
  .github/workflows/push.yaml
Labels: area/ci
