Repository stefanprodan/timoni, pull requests merged in 2023-09, with the labels that each got.

#179 Fix panic when waiting for global resources
  cmd/timoni/apply.go
  cmd/timoni/apply_test.go
  cmd/timoni/bundle_apply.go
  cmd/timoni/testdata/module/templates/config.cue
  cmd/timoni/testdata/module/templates/namespace.cue
Labels: bug, area/runtime

#166 Add a YAML CRD to CUE IR conversion function
  go.mod
  go.sum
  internal/engine/crd.go
  internal/engine/crd_test.go
  internal/engine/testdata/crd/source-controller.crds.yaml
Labels: enhancement, area/engine

#183 Prefix Kubernetes flags
  cmd/timoni/main.go
Labels: area/cli

#184 Use Go 1.21 stdlib
  CONTRIBUTING.md
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/timoni/bundle_apply.go
  cmd/timoni/bundle_build.go
  cmd/timoni/bundle_lint.go
  docs/install.md
  go.mod
  go.sum
  internal/runtime/reader.go
Labels: dependencies

#182 Add cosign signing and verification for modules
  cmd/timoni/mod_pull.go
  cmd/timoni/mod_push.go
  internal/signutil/cosign.go
  internal/signutil/doc.go
  internal/signutil/signutil.go
Labels: enhancement, area/cli

#185 Enforce Kubernetes min version for modules
  api/v1alpha1/instance.go
  cmd/timoni/build_test.go
  cmd/timoni/testdata/module/timoni.cue
  docs/module.md
  examples/minimal/templates/config.cue
  examples/minimal/timoni.cue
  internal/engine/module_builder.go
Labels: enhancement, area/api, area/engine

#186 docs: Sign and verify modules with Cosign
  cmd/timoni/mod_push.go
  docs/github-actions.md
  docs/index.md
  docs/module-semver.md
  docs/module-sign.md
  mkdocs.yml
Labels: area/docs

#188 docs: Add Nix installation instructions
  docs/install.md
Labels: area/docs

#189 bundle: Fix values merge with module defaults
  cmd/timoni/build_test.go
  cmd/timoni/testdata/module/templates/config.cue
  cmd/timoni/testdata/module/values.cue
  internal/engine/module_builder.go
Labels: bug, area/bundles

#190 docs: Add the Runtime API to comparison doc
  docs/bundle-runtime.md
  docs/comparison.md
Labels: area/docs

#192 Add cmd for generating CUE definitions from Kubernetes CRDs
  cmd/timoni/main_test.go
  cmd/timoni/mod_import.go
  cmd/timoni/mod_import_crd.go
  cmd/timoni/mod_import_crd_test.go
  cmd/timoni/testdata/crd/golden/cue.mod/gen/acme.cert-manager.io/challenge/v1/types_gen.cue
  cmd/timoni/testdata/crd/golden/cue.mod/gen/acme.cert-manager.io/order/v1/types_gen.cue
  cmd/timoni/testdata/crd/golden/cue.mod/gen/cert-manager.io/certificate/v1/types_gen.cue
  cmd/timoni/testdata/crd/golden/cue.mod/gen/cert-manager.io/certificaterequest/v1/types_gen.cue
  cmd/timoni/testdata/crd/golden/cue.mod/gen/cert-manager.io/clusterissuer/v1/types_gen.cue
  cmd/timoni/testdata/crd/golden/cue.mod/gen/cert-manager.io/issuer/v1/types_gen.cue
  cmd/timoni/testdata/crd/source/cert-manager.crds.yaml
  go.mod
  go.sum
  internal/engine/crd_test.go
  internal/engine/importer.go
  internal/engine/importer_test.go
  internal/engine/testdata/crd/source-controller.crds.yaml
Labels: enhancement, area/cli

#194 Add cmd for importing Kubernetes API schemas
  cmd/timoni/mod_import.go
  cmd/timoni/mod_import_crd.go
  cmd/timoni/mod_import_k8s.go
Labels: area/ux, area/cli

#197 Add commands for vendoring CUE schemas
  cmd/timoni/main_test.go
  cmd/timoni/mod_vendor.go
  cmd/timoni/mod_vendor_crd.go
  cmd/timoni/mod_vendor_crd_test.go
  cmd/timoni/mod_vendor_k8s.go
  cmd/timoni/testdata/crd/golden/cue.mod/gen/acme.cert-manager.io/challenge/v1/types_gen.cue
  cmd/timoni/testdata/crd/golden/cue.mod/gen/acme.cert-manager.io/order/v1/types_gen.cue
  cmd/timoni/testdata/crd/golden/cue.mod/gen/cert-manager.io/certificate/v1/types_gen.cue
  cmd/timoni/testdata/crd/golden/cue.mod/gen/cert-manager.io/certificaterequest/v1/types_gen.cue
  cmd/timoni/testdata/crd/golden/cue.mod/gen/cert-manager.io/clusterissuer/v1/types_gen.cue
  cmd/timoni/testdata/crd/golden/cue.mod/gen/cert-manager.io/issuer/v1/types_gen.cue
Labels: area/cli

#199 Document Kubernetes APIs and CRDs vendoring
  README.md
  api/v1alpha1/ignore.go
  docs/index.md
  docs/module.md
  examples/minimal/README.md
  examples/minimal/cue.mod/gen/k8s.io/api/admission/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/admission/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/admissionregistration/v1/doc_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/admissionregistration/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/admissionregistration/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/apps/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/authentication/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/authentication/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/authorization/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/authorization/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/autoscaling/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/autoscaling/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/autoscaling/v2/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/autoscaling/v2/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/batch/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/batch/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/certificates/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/certificates/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/coordination/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/coordination/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/core/v1/annotation_key_constants_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/core/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/core/v1/well_known_labels_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/discovery/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/discovery/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/discovery/v1/well_known_labels_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/events/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/events/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/networking/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/networking/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/networking/v1/well_known_annotations_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/node/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/node/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/policy/v1/doc_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/policy/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/policy/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/rbac/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/rbac/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/scheduling/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/scheduling/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/storage/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/storage/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/doc_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_jsonschema_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/apis/meta/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/runtime/splice_go_gen.cue
  examples/minimal/debug_tool.cue
  examples/minimal/debug_values.cue
  examples/minimal/go.mod
  examples/minimal/go.sum
  examples/minimal/values.cue
Labels: area/docs

#203 Add registry login/logout commands
  cmd/timoni/artifact_pull.go
  cmd/timoni/artifact_push.go
  cmd/timoni/mod_pull.go
  cmd/timoni/mod_push.go
  cmd/timoni/registry.go
  mkdocs.yml
Labels: area/ux, area/cli
