Repository stefanprodan/timoni, pull requests merged in 2023-07, with the labels that each got.

#128 feat: add YAML and JSON support for bundles
  cmd/timoni/bundle_build_test.go
  internal/engine/bundle_builder.go
  internal/engine/injector.go
Labels: enhancement, area/bundles

#133 Document how to build bundles from JSON/YAML
  docs/bundles.md
Labels: area/docs, area/bundles

#135 Normalise the SLSA provenance files
  .github/workflows/release.yaml
  docs/install.md
Labels: area/ci

#136 ci: Pin cuelang version to v0.5.0
  .github/dependabot.yaml
  .github/workflows/build.yaml
Labels: area/ci

#138 Add stale resources to the dry run output
  cmd/timoni/apply.go
  cmd/timoni/bundle_apply.go
  cmd/timoni/dyff.go
Labels: area/cli, area/runtime

#134 Add completion for instances and namespaces
  cmd/timoni/apply.go
  cmd/timoni/build.go
  cmd/timoni/completion_funcs.go
  cmd/timoni/delete.go
  cmd/timoni/inspect_module.go
  cmd/timoni/inspect_resources.go
  cmd/timoni/inspect_values.go
  cmd/timoni/list.go
  cmd/timoni/main.go
  cmd/timoni/status.go
  internal/runtime/storage.go
Labels: area/ux, area/cli

#137 Prettier and more colorized output for the apply commands
  cmd/timoni/apply.go
  cmd/timoni/bundle_apply.go
  cmd/timoni/bundle_delete.go
  cmd/timoni/delete.go
  cmd/timoni/dyff.go
  cmd/timoni/log.go
  cmd/timoni/main.go
  go.mod
  go.sum
Labels: area/ux, area/cli

#141 Colorize `inspect`, `status`, & `bundle lint`
  cmd/timoni/bundle_lint.go
  cmd/timoni/completion_funcs.go
  cmd/timoni/inspect_resources.go
  cmd/timoni/inspect_values.go
  cmd/timoni/log.go
  cmd/timoni/main.go
  cmd/timoni/status.go
Labels: area/ux, area/cli

#147 Fix test flake for `timoni bundle build`
  cmd/timoni/main_test.go
Labels: area/cli

#152 fix: unquote instance name
  internal/engine/bundle_builder.go
  internal/engine/bundle_builder_test.go
Labels: area/engine, area/bundles

#150 Introduce a minimal module for `timoni mod init`
  .github/workflows/e2e.yaml
  Makefile
  cmd/timoni/mod_init.go
  docs/module.md
  examples/minimal/README.md
  examples/minimal/cue.mod/gen/k8s.io/api/apps/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/apps/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/core/v1/annotation_key_constants_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/core/v1/doc_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/core/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/core/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/core/v1/well_known_labels_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/api/core/v1/well_known_taints_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/api/resource/amount_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/api/resource/math_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/api/resource/quantity_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/api/resource/suffix_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/apis/meta/v1/duration_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/apis/meta/v1/group_version_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/apis/meta/v1/meta_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/apis/meta/v1/register_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/apis/meta/v1/time_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/apis/meta/v1/time_proto_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/apis/meta/v1/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/apis/meta/v1/watch_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/runtime/allocator_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/runtime/codec_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/runtime/conversion_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/runtime/converter_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/runtime/doc_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/runtime/embedded_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/runtime/helper_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/runtime/interfaces_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/runtime/negotiate_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/runtime/swagger_doc_generator_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/runtime/types_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/runtime/types_proto_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/types/doc_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/types/namespacedname_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/types/nodename_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/types/patch_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/types/uid_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/util/intstr/intstr_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/watch/doc_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/watch/filter_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/watch/mux_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/watch/streamwatcher_go_gen.cue
  examples/minimal/cue.mod/gen/k8s.io/apimachinery/pkg/watch/watch_go_gen.cue
  examples/minimal/cue.mod/module.cue
  examples/minimal/cue.mod/pkg/timoni.sh/core/v1alpha1/image.cue
  examples/minimal/go.mod
  examples/minimal/go.sum
  examples/minimal/templates/config.cue
  examples/minimal/templates/configmap.cue
  examples/minimal/templates/deployment.cue
  examples/minimal/templates/service.cue
  examples/minimal/templates/serviceaccount.cue
  examples/minimal/timoni.cue
  examples/minimal/values.cue
Labels: area/docs, area/ux, area/cli

#155 Update dependencies
  go.mod
  go.sum
Labels: area/runtime, dependencies

#156 Fail fast when waiting for resources
  cmd/timoni/apply.go
  cmd/timoni/bundle_apply.go
Labels: area/runtime
