Repository stefanprodan/timoni, pull requests merged in 2024-06, with the labels that each got.

#396 Doc typo fix
  docs/bundle-secrets.md
Labels: area/docs

#366 Refactor `cmd/timoni` and extract reconciler logic to dedicated package
  cmd/timoni/apply.go
  cmd/timoni/apply_test.go
  cmd/timoni/artifact_list.go
  cmd/timoni/artifact_pull.go
  cmd/timoni/artifact_push.go
  cmd/timoni/artifact_tag.go
  cmd/timoni/bundle_apply.go
  cmd/timoni/bundle_apply_test.go
  cmd/timoni/bundle_delete.go
  cmd/timoni/bundle_status.go
  cmd/timoni/bundle_vet.go
  cmd/timoni/delete.go
  cmd/timoni/inspect_resources.go
  cmd/timoni/log.go
  cmd/timoni/logger.go
  cmd/timoni/main.go
  cmd/timoni/main_test.go
  cmd/timoni/mod_init.go
  cmd/timoni/mod_list.go
  cmd/timoni/mod_pull.go
  cmd/timoni/mod_push.go
  cmd/timoni/mod_vendor_crd.go
  cmd/timoni/mod_vendor_k8s.go
  cmd/timoni/mod_vet.go
  cmd/timoni/runtime_build.go
  cmd/timoni/status.go
  internal/dyff/dyff.go
  internal/dyff/dyff_test.go
  internal/logger/logger.go
  internal/reconciler/interactive.go
  internal/reconciler/reconciler.go
  internal/reconciler/types.go
Labels: enhancement, area/cli

#401 Update `cuelang.org/go` to v0.9.1
  go.mod
  go.sum
  internal/engine/module_builder.go
Labels: dependencies

#407 Add language version to all modules
  blueprints/starter/cue.mod/module.cue
  cmd/timoni/main.go
  cmd/timoni/testdata/module/cue.mod/module.cue
  examples/minimal/cue.mod/module.cue
  examples/redis/cue.mod/module.cue
  go.mod
  go.sum
  internal/engine/testdata/module/cue.mod/module.cue
Labels: area/blueprints

#408 Update dependencies to Kubernetes v1.30.2
  blueprints/starter/values.cue
  go.mod
  go.sum
  internal/testutils/matchers.go
Labels: dependencies
